/** The presentation and chart language shared by the editor, exporter, and agents. */
export const CONSULTANCY_PRESENTATION_STANDARD = {
  name: "Berenschot 2026",
  style: {
    name: "Berenschot 2026",
    background: "FFFFFF",
    foreground: "1F345E",
    accent: "0075AB",
    muted: "66758A",
    fontFace: "Arial",
  },
  colors: {
    navy: "1F345E",
    blue: "0075AB",
    cyan: "41B6E6",
    gold: "FAB900",
    paleBlue: "EAF4FD",
    warmBrown: "BA6E16",
  },
  report: "Strategie Trendsonderzoek 2026",
  website: "https://www.berenschot.nl/",
} as const;

export const CONSULTANCY_SLIDE_COMPONENTS = [
  {
    id: "cover",
    name: "Titelpagina",
    description: "Marineblauwe achtergrond, gouden zijlijn, grote witte titel en korte ondertitel.",
  },
  {
    id: "section",
    name: "Sectiepagina",
    description: "Donkere overgangsslide met één sectietitel en één kernzin.",
  },
  {
    id: "content",
    name: "Kernboodschap",
    description: "Witte slide met marineblauwe kop, goud accent en beknopte onderbouwing.",
  },
  {
    id: "two-column",
    name: "Inzicht en implicatie",
    description: "Twee kolommen voor de bevinding en de keuze of aanbeveling.",
  },
  {
    id: "chart",
    name: "Grafiek met bronregel",
    description: "Bewerkbare grafiek in blauw met eenheid, korte duiding en zichtbare bron.",
  },
] as const;

export const CONSULTANCY_CHART_COMPONENTS = [
  {
    id: "strategy-translation",
    name: "Strategie naar marktvertaling",
    type: "bar",
    unit: "%",
    source: "Strategie Trendsonderzoek 2026, p. 12, fig. 4",
    categories: [
      "Bestaansrecht/doel helder",
      "Missie/visie geformuleerd",
      "Heldere strategische keuzes",
      "Segmentatie/propositie aangepast",
      "Waardepropositie uitgewerkt",
    ],
    values: [94, 83, 57, 46, 41],
  },
  {
    id: "planning-horizon",
    name: "Strategische planningshorizon",
    type: "bar",
    unit: "%",
    source: "Strategie Trendsonderzoek 2026, p. 13, fig. 5",
    categories: ["Korter dan 1 jaar", "1–3 jaar", "3–5 jaar", "Langer dan 5 jaar"],
    values: [2, 43, 41, 13],
    note: "Door afronding tellen de percentages op tot 99%.",
  },
  {
    id: "cost-drivers",
    name: "Kosten, lonen en prijzen",
    type: "bar",
    seriesName: "Gemiddelde stijging",
    unit: "%",
    source: "Strategie Trendsonderzoek 2026, p. 8, fig. 2",
    categories: ["Kostenstijging", "Loonstijging", "Prijsstijging"],
    values: [4.1, 3.4, 3.8],
  },
  {
    id: "ai-use-cases",
    name: "AI-toepassingen",
    type: "bar",
    unit: "%",
    source: "Strategie Trendsonderzoek 2026, p. 21, fig. 11",
    categories: ["Tekst samenvatten", "Efficiënter werken", "Rapporten voorbereiden"],
    values: [60, 54, 53],
  },
  {
    id: "ai-investment-sectors",
    name: "AI-investeringen per sector",
    type: "bar",
    unit: "%",
    source: "Strategie Trendsonderzoek 2026, p. 23, fig. 12",
    categories: [
      "Financiële dienstverlening",
      "Overheid en openbaar bestuur",
      "Onderwijs en onderzoek",
      "Zakelijke diensten, media en ICT",
      "Zorg en life sciences",
      "Energie, afval, telecom en nutsvoorzieningen",
      "Retail",
      "Transport en logistiek",
      "Totaal",
      "Bouw en woningcorporaties",
      "Industrie",
      "Stichtingen, NGO’s en belangenorganisaties",
      "Agri en food",
      "Cultuur, sport en recreatie",
    ],
    values: [100, 83, 78, 76, 76, 71, 71, 69, 69, 65, 58, 52, 50, 50],
  },
  {
    id: "geopolitics-trend",
    name: "Geopolitiek op de strategische agenda",
    type: "line",
    unit: "%",
    source: "Strategie Trendsonderzoek 2026, p. 27, fig. 13",
    categories: ["2024", "2025", "2026"],
    values: [6, 12, 18],
  },
  {
    id: "export-markets",
    name: "Interessante exportmarkten",
    type: "bar",
    unit: "%",
    source: "Strategie Trendsonderzoek 2026, p. 29, fig. 14",
    categories: ["Nederland", "West-Europa", "Noord-Amerika", "Noord-Europa", "Zuid-Europa"],
    values: [79, 48, 25, 25, 19],
  },
] as const;

export const CONSULTANCY_PRESENTATION_GUIDANCE = [
  "Use the single shared Berenschot 2026 presentation standard for every slide and chart.",
  "For .t3deck.json, set style to { name: 'Berenschot 2026', background: 'FFFFFF', foreground: '1F345E', accent: '0075AB', muted: '66758A', fontFace: 'Arial' }.",
  "Use a navy cover or section slide; use white content slides with navy headings, blue chart marks, and a small gold accent.",
  "Keep one main point per slide. Summarize source rows rather than pasting dense paragraphs; use a two-column slide for insight and implication.",
  "For charts, set chart.unit (for example '%'), label categories, start bar axes at zero, and add a visible source with page or URL. Native PowerPoint charts should stay editable.",
  "In a .t3deck.json chart slide, use layout 'chart' and chart with the same type, categories, series, unit, and source fields as a t3-chart block in chat. Supported types are bar, line, area, pie, doughnut, and scatter.",
  "The seven report charts are examples and source data for that report. Do not reuse their values for unrelated client data.",
].join("\n");
